### ISSUE TITLE
Move to nix-community

### ISSUE THREAD

**Issue by zimbatm** [nix-community/nix-unstable-installer#41]
**Is your feature request related to a problem? Please describe.**

This project is useful to everybody and should belong to the community.

**Describe the solution you'd like**

Move the repo to the nix-community org.

**Describe alternatives you've considered**

Move to the NixOS org, but that's more complicated.

**Additional context**

@lilyinstarlight what do you think?

**Comment by lilyinstarlight** [comment]
Yes, I agree nix-community is probably a good place to migrate this repo if we wanted to do that

**Comment by zimbatm** [comment]
Alright, done! Would you be interested in becoming the official maintainer?

**Comment by lilyinstarlight** [comment]
Sure! I can be the official maintainer

**Comment by zimbatm** [comment]
Awesome. Thanks for all your help on this project.

**Comment by lilyinstarlight** [comment]
Do I need to be invited to the nix-community org to be an official maintainer of a repo or no?

Thank you @zimbatm!

**Comment by zimbatm** [comment]
you should have received an invite to become part of the corresponding nix-unstable-installer team

**Comment by lilyinstarlight** [comment]
Hmmm, I didn't receive an email and I also don't see the banner at the top of https://github.com/nix-community saying I received an invite either

**Comment by zimbatm** [comment]
fixed, I had invited the wrong person :S

**Comment by lilyinstarlight** [comment]
Oops yeah, that would do it

I've received the invite and it seems to be good now though, thank you!
