### ISSUE TITLE
libunwind

### ISSUE THREAD

**Issue by jmikedupont2** [nix-community/nix-unstable-installer#59]
/nix/store/cc5kql8wzd0zkz7vx7zjc2rf1rsyzmn2-nix-2.21.0pre20240214_d857914/bi\
n/nix-store: error while loading shared libraries: libunwind.so.8: cannot op\en shared object file: No such file or directory
/tmp/nix-binary-tarball-unpack.CVL8CoQFnV/unpack/nix-2.21.0pre20240214_d8579\
14-x86_64-linux/install: unable to register valid paths

**Comment by jmikedupont2** [comment]
https://github.com/NixOS/nix/issues/10113 same issue in main repo

**Comment by zimbatm** [comment]
yeah, this is an upstream issue. this repo is just re-posting the builds that have been published by hydra.
